---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-token
  namespace: homeassistant
spec:
  encryptedData:
    HA_TOKEN: AgAUyLxLrEXunYX7+dmXhf0xyd0ICDVHh1xgRU2cGpY8g8AImWId1ZIuYTVy/IY75R1l3wpUyWt4ispSp/Gjb0f9//5AWDW6/RFjfnVCJBLg+emVTMvqwfSoCMpofngq6Ax1rzg+hAZxTJoKCBiTy/bvsshHw8oS6Bh2VQ/OO6HuhRgwKuEwJ8gZwsJ062KCE0atTC9CBgW04V5N0vWaSb13XDBQ23OmMYZt6cL3zjZXjFKNwtL/bekBclzlY26+ZKMj07TnFScVzS53tCVxZBPc6U+pVrTn8hbK2mbmbNUjMMJhPCQS8xoKR1n8cynb5xIumAtVbU/i7bylVR6NFKeVA6PA6EVtpJhFZ6TRvgIIQHXzNXaBFla3cp57yDixEAvp6NfGQ+PbmSuHe9K42gxmIAs+y+i2zHKtvilLEgPbxMd1VhpY+ytiAR47vn1vo76fzUjOX1dyJjGuZfqH7nQvqENLbUengymTd1OL5t976QryfiPysgV8Ma2gUT8c9S1PPSqQW78WkRMhjbHHZpCHGl5HAsxMuMl2oU9bUXn/0Dq0BhiuP69B1D5/GKUPsLtP9khreH24QIwN4OA8etoviGZusYKHgD7q1qZUvKjf8NLY3eXiyjd4liKO8SkNoOWt2tyUx/CVJB5/Es8M+5YyA6zF2320BUZ9NsXab/ibqdYADikELMM7ZEThXQhOvI4MWPpBGGd7znhFpRkvDUMKWZvKWAomO13Qi5d6qgoSDq1KsgPPD2/2PtKWmOzRzWdqA4olAEX7SFM+dOKFsx0BXKv/x2mJWKMesmKkv0feBBkvogbCyQu56FiYIW5eaftSdXzPA+a9ZBXtVI+BnEoBGM6+8m3sdelPxpBaWCymK5h9VAG69/VDgTdZTWCUko4NqkDZngQynf0PLqFWB/cWym/4spM3MZ+4fzgvgGPdN4Jlk+ftuZ8=
  template:
    metadata:
      name: homeassistant-token
      namespace: homeassistant
    type: Opaque
