apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
  namespace: homeassistant
  labels:
    app: music-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: k8s-cp
      containers:
        - name: music-assistant
          image: ghcr.io/music-assistant/server:latest
          ports:
            - containerPort: 8095
              name: http
          env:
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: music-assistant-data
