apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
